### ISSUE TITLE
Заменить лого [bruh] 

### ISSUE THREAD

**Issue by cryals** [space-sunrise/space-station-14#10]
# По просьбе splikzerys, вот сразу готовое:
16x16
![icon-16x16.png](https://github.com/space-sunrise/space-station-14/assets/99600368/06bf20b7-7ced-48b8-9093-556a4f2a62e7) 
24x24
![icon-24x24.png](https://github.com/space-sunrise/space-station-14/assets/99600368/e5b0ba5a-2df3-474c-a237-d07474c559a2)
32x32
![icon-32x32.png](https://github.com/space-sunrise/space-station-14/assets/99600368/9c72c473-ebbe-44d6-a191-5061c554c33d) 
48x48
![icon-48x48.png](https://github.com/space-sunrise/space-station-14/assets/99600368/d3af7658-d6bc-41f5-9c8f-1c45c1679f73)
64x64
![icon-64x64.png](https://github.com/space-sunrise/space-station-14/assets/99600368/d8be57a1-ca69-43d9-9c30-41cb524248d8) 
128x128
![icon-128x128.png](https://github.com/space-sunrise/space-station-14/assets/99600368/21c8092a-cce6-4d35-af83-bf863767aabd)
256x256
![icon-256x256.png](https://github.com/space-sunrise/space-station-14/assets/99600368/08ca7edf-011a-47f9-a395-9636ccab2bca)
512x512
![icon-512x512.png](https://github.com/space-sunrise/space-station-14/assets/99600368/9c2fbc6b-ced8-49f3-ad2c-087399cc5b24)

---

# Архив:
![icons.zip](https://github.com/user-attachments/files/15524725/icons.zip)

**Comment by gghj31621** [comment]
> Круто, но хотелось бы ПР

Приеду домой, кину
