### ISSUE TITLE
[TOOLSHED REQUEST] Обновление мышей

### ISSUE THREAD

**Issue by Rinary1** [space-sunrise/space-station-14#154]
Идея такова:

Добавить мышам возможность грызть провода, как в сс13(укус провода = смерть), так-же добавить событие с нашествием мышей, эти вещи немного разбавят геймплей инженеров(прийдёться бегать по техах в поисках обрывов)

**Comment by VigersRay** [comment]
а че им сейчас мешает просто атаковать провод?

**Comment by Rinary1** [comment]
> а че им сейчас мешает просто атаковать провод?

разве они так могут? + не логично

**Comment by VigersRay** [comment]
> > а че им сейчас мешает просто атаковать провод?
> 
> разве они так могут? + не логично
> 
> upd: зашёл на локалку, заспавнил крысу, в хот баре нет боевого, даже если поставить боевой в хот бар он не будет работать, следовательно крысы сейчас это сугубо мясо для повара

Ты путаешь мышей и крыс...
Крысы это армия крысиного короля, у них есть боевой режим. 
У мышей же нету боевого режима да, потому что это роль для тех кто проебал свою жизнь.

**Comment by Rinary1** [comment]
> > > а че им сейчас мешает просто атаковать провод?
> > 
> > 
> > разве они так могут? + не логично
> > upd: зашёл на локалку, заспавнил крысу, в хот баре нет боевого, даже если поставить боевой в хот бар он не будет работать, следовательно крысы сейчас это сугубо мясо для повара
> 
> Ты путаешь мышей и крыс... Крысы это армия крысиного короля, у них есть боевой режим. У мышей же нету боевого режима да, потому что это роль для тех кто проебал свою жизнь.

сори, затупил, ну в любом случае я имел ввиду мышей

**Comment by VigersRay** [comment]
оффы добавили возможность мышам кусаться (без урона)
