### ISSUE TITLE
Злой двойник некорректно работает на слаймолюдах

### ISSUE THREAD

**Issue by pxc1984** [space-sunrise/space-station-14#24]
## Description

Проблема в том, что когда слаймолюд использует Герас(действие превращения в минислайма и обратно), система EvilTwinSystem.cs пытается перевыдать слаймолюду роль злого двойника и его цели, что вызывает ошибку изза чего слайм-Герас не удаляется, а в дебаг сборке это вообще крашит сервер.

**Reproduction**

1. Зайти с клиента A на сервер за персонажа-слаймолюда
2. Вызвать роль злого двойника и зайти за него с клиента B
3. Использовать действие превращения в слайма и обратно (можно несколько раз)

**Screenshots**

![image](https://github.com/space-sunrise/space-station-14/assets/77161122/fcde2c60-0f46-4074-b87c-7a53d8ec5d43)

**Additional context**

Очевидным фиксом будет проверять, есть ли необходимая роль у mind:

EvilTwinSystem.cs:
```
...
if (_roleSystem.MindHasRole<TraitorRoleComponent>(mindId))
    return;
...
```
Но при применении этого решения вылезает еще букет проблем, таких как:
* После превращения в Герас теряется прогресс убийства цели и цель на убийство пропадает
* При попытке удаления такого злого двойника не совпадают айдишники и вылезает ошибка (не критичная)

**Comment by Rinary1** [comment]
https://github.com/space-wizards/space-station-14/pull/29731

не актуально
