### ISSUE TITLE
Способность мима не ограничивает игрока, когда тот пытается поставить невидимую стену в препятствие, так как сломана функция IsTileBlocked

### ISSUE THREAD

**Issue by pofitlo-Git** [space-sunrise/space-station-14#373]
## Description

это задевает не только способность мима, но и также остальные аспекты игры, но с мимом самое заметное

если вы попытаетесь поставить невидимую стену в препятствие (стена, баллон и т.д.), то вы сможете спокойно это сделать, в то время как должно вывестись сообщение "тут заблокировано" или типо того

ошибка эта чисто местная, у визордов проблем нет

**Reproduction**

Попытайтесь поставить стену мима в цистерну, которая должна являться препятствием, и у вас получится. 
**Screenshots**

![image](https://github.com/user-attachments/assets/998c4c91-758d-4185-8e36-d0d1567cd254)

![image](https://github.com/user-attachments/assets/4800a004-600b-4b0d-a797-c05209754643)

**Additional context**

Я даже могу указать конкретную причину, что вызывает эту ошибку. Это ряд функций, которые у вас, почему-то, отличаются от функций визардов. я скину скриншот откуда всё начинается, но так-же, эти несоответствия идут и в глубь в плоть до того, что одна функция чуть ли не полностью переписана. 

находится, кстати, этот код в пространстве имен: Robust.Shared.GameObjects.EntityLookupSystem

**Comment by pofitlo-Git** [comment]
дополню: можно построить стену в стене и т.д.

**Comment by Rinary1** [comment]
> ## Description
> это задевает не только способность мима, но и также остальные аспекты игры, но с мимом самое заметное
> 
> если вы попытаетесь поставить невидимую стену в препятствие (стена, баллон и т.д.), то вы сможете спокойно это сделать, в то время как должно вывестись сообщение "тут заблокировано" или типо того
> 
> ошибка эта чисто местная, у визордов проблем нет
> 
> **Reproduction**
> 
> Попытайтесь поставить стену мима в цистерну, которая должна являться препятствием, и у вас получится. **Screenshots**
> 
> ![image](https://private-user-images.githubusercontent.com/175959799/366047085-998c4c91-758d-4185-8e36-d0d1567cd254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTg0MzAsIm5iZiI6MTcyNjMxODEzMCwicGF0aCI6Ii8xNzU5NTk3OTkvMzY2MDQ3MDg1LTk5OGM0YzkxLTc1OGQtNDE4NS04ZTM2LWQwZDE1NjdjZDI1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxMjQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTZlZWM0YTQ5MWIxMWNiMDIzODRkNTExYWExYjFiY2JmMjlmYjVmYWJmZjFlMWMyNjdhYzc1OTMyODJkNjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7qZ93exIPIo06arbC8BqANJwvpn0QN0c2SaEAqB1whI)
> 
> ![image](https://private-user-images.githubusercontent.com/175959799/366047144-4800a004-600b-4b0d-a797-c05209754643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTg0MzAsIm5iZiI6MTcyNjMxODEzMCwicGF0aCI6Ii8xNzU5NTk3OTkvMzY2MDQ3MTQ0LTQ4MDBhMDA0LTYwMGItNGIwZC1hNzk3LWMwNTIwOTc1NDY0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxMjQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDdjZWQ4NjY5ZjNiYjQyNDViNGY3OGMzZWQ5NzI2ZjE5ZGE0ODQ4MmYyMDQ1N2JjMjI2Zjg1NmJmNDQ5N2RhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VWIwmA_50B8iwBARXTXUbpCGml9GuCGBf307jHatxGY)
> 
> **Additional context**
> 
> Я даже могу указать конкретную причину, что вызывает эту ошибку. Это ряд функций, которые у вас, почему-то, отличаются от функций визардов. я скину скриншот откуда всё начинается, но так-же, эти несоответствия идут и в глубь в плоть до того, что одна функция чуть ли не полностью переписана.
> 
> находится, кстати, этот код в пространстве имен: Robust.Shared.GameObjects.EntityLookupSystem

Ты что-то путаешь, ведь я только что посмотрел репо оффов и то место что ты показывал с нашей стороны идентично с местом у оффов в репо
![image](https://github.com/user-attachments/assets/340e8037-e997-493d-9b0e-c27acb98442f)


К тому же это движок, который невозможно редактировать

**Comment by Rinary1** [comment]
что же по поводу бага с постройкой стены в стене, на сборке санрайза с апстримом, данной проблемы нет, если не спавнить стену через песок то через меню постройки можно лишь поставить призрак но никак не построить саму стенку. На счёт мима я бы не назвал это проблемой. Ведь он не двигает предмети способностью и для него это лишь приём актёрского мастерства
