### ISSUE TITLE
СПИСОК ТОГО ЧТО НАДО СДЕЛАТЬ

### ISSUE THREAD

**Issue by SplikZerys** [space-sunrise/space-station-14#501]
Для себя заметки по большей части делаю

- [ ] На магистрате не засчитывается время на командвоании.
- [ ] Открытие представителя ЦК и ещё какой-то роли(кажется адьютант).
- [x] Лодаут бумбокса на Ласте
- [ ] Добавить тестово петов (игрокам закомментить лодаут)
- [ ] Добавить всех петов

**Comment by VigersRay** [comment]
Сюда желательно писать только о багах, предложения и планы писать сюда:
https://github.com/space-sunrise/space-station-14/discussions/categories/ideas
