### ISSUE TITLE
портировать кз в игровой гайдбук

### ISSUE THREAD

**Issue by lzk228** [space-sunrise/space-station-14#502]
нужно портировать кз в игровой гайдбук по той же причине по которой нам нужны правила прямо в игре

**Comment by VigersRay** [comment]
Я еще 3 месяца назад это предлагал сделать, но модераторы сказали что я долбоеб.

**Comment by lzk228** [comment]
> Я еще 3 месяца назад это предлагал сделать, но модераторы сказали что я долбоеб.

сделай это сам

**Comment by VigersRay** [comment]
> > Я еще 3 месяца назад это предлагал сделать, но модераторы сказали что я долбоеб.
> 
> сделай это сам

Я не хочу ебаться с хуйней которую может написать буквально любой чел который имеет IQ выше 70 и умеет юзать CTRL+C и CTRL+V. 
У меня есть свои дела.

**Comment by VigersRay** [comment]
Сюда желательно писать только о багах, предложения и планы писать сюда:
https://github.com/space-sunrise/space-station-14/discussions/categories/ideas
