### ISSUE TITLE
Не хватает вариаций двойных шлюзов

### ISSUE THREAD

**Issue by AverageNotDoingAnythingEnjoyer** [space-sunrise/space-station-14#519]
## Описание

На данный момент у новых двойных шлюзов нет вариаций без доступов и версий для подотделов (двойной шлюз карго с доступами утилей).

**Воспроизведение**

Открыть меню спавна сущностей, ввести "двойной", сравнить с поиском по слову "стекляный".

**Медиа**

Нет

**Дополнительный контекст**

Необходимо для упрощения маппинга. Возможно сделаю сам и подкорректирую названия шлюзов в коде под стандарты Визов, но не знаю когда смогу.

**Comment by VigersRay** [comment]
Сюда желательно писать только о багах, предложения и планы писать сюда:
https://github.com/space-sunrise/space-station-14/discussions/categories/ideas
