### ISSUE TITLE
[Предложение] Переработка системы с гипоспреем

### ISSUE THREAD

**Issue by kanopus952** [space-sunrise/space-station-14#604]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**

Реворк новой фичи с невозможностью использовать гипоспрей при наличии скафандра. Ломает многие уже существующие механы
**Опишите желаемое**

Добавить компонент, при помощи которого можно сделать вайтлист скафандру на возможность использования того или иного гипоспрея. Обычные и инженерные скафандры не будут иметь защиты к гипо, скафандры глав/сб будут иметь защиту к гипоручке, скафандры ЯО будут иметь защиту от станционных гипоспреев, но не иметь защиты от гипоспрея мед.борга синдиката и гипоручки. 
**Дополнительный контекст**

**Comment by kanopus952** [comment]
Пожалуй @Rinary1

**Comment by Rinary1** [comment]
> **Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
> 
> Реворк новой фичи с невозможностью использовать гипоспрей при наличии скафандра. Ломает многие уже существующие механы
> **Опишите желаемое**
> 
> Добавить компонент, при помощи которого можно сделать вайтлист скафандру на возможность использования того или иного гипоспрея. Обычные и инженерные скафандры не будут иметь защиты к гипо, скафандры глав/сб будут иметь защиту к гипоручке, скафандры ЯО будут иметь защиту от станционных гипоспреев, но не иметь защиты от гипоспрея мед.борга синдиката и гипоручки. 
> **Дополнительный контекст**
> 

Хуйня, уже есть другая предложка, через же, посмотри дс

**Comment by KaiserMaus** [comment]
> > **Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
> > 
> > Реворк новой фичи с невозможностью использовать гипоспрей при наличии скафандра. Ломает многие уже существующие механы
> > **Опишите желаемое**
> > 
> > Добавить компонент, при помощи которого можно сделать вайтлист скафандру на возможность использования того или иного гипоспрея. Обычные и инженерные скафандры не будут иметь защиты к гипо, скафандры глав/сб будут иметь защиту к гипоручке, скафандры ЯО будут иметь защиту от станционных гипоспреев, но не иметь защиты от гипоспрея мед.борга синдиката и гипоручки.
> > **Дополнительный контекст**
> 
> Хуйня, уже есть другая предложка, через эп, посмотри дс

А как на счёт сделать защиту привязанной к шлему скафандра? 
Снял шлем>можно уколить

**Comment by VigersRay** [comment]
Частично исправлено в https://github.com/space-sunrise/space-station-14/commit/80c88c2b9747549168408557d863fe133247befe
Возможно стоит переоткрыть но с новой темой.
