### ISSUE TITLE
Баг с ксено и яутжи

### ISSUE THREAD

**Issue by SplikZerys** [space-sunrise/space-station-14#634]
Если на расах ксено и яутжи поспать, то навсегда теряется зрение

**Comment by pxc1984** [comment]
https://github.com/user-attachments/assets/69c5ceba-32b1-4e0d-acf0-f78ceba3a97d

**Comment by pxc1984** [comment]
Проблема заключается в хирургии. У яутж и ксеносов нет органа глаз, поэтому у них по идее вообще зрения не должно было быть.

**Comment by VigersRay** [comment]
Исправлено https://github.com/space-sunrise/space-station-14/pull/647
