### ISSUE TITLE
Vampire: Священник может стать Вампиром

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#636]
## Описание
Ну как бы Священник, Пользователь библии и заклятый враг вампиров может  сам стать вампиром, причем против Вампиров действует Библия и Святая вода 
**Воспроизведение**
Зайти за священника и игра может выдать
![Снимок экрана 2024-11-15 112903](https://github.com/user-attachments/assets/609080ea-3d4c-40b2-8d32-2f640871bc2d)
 Вампира

**Медиа**
 Если есть возможность, прикрепите скриншот/видео, показывающие саму проблему и шаги ее воспроизведения.

**Comment by Rinary1** [comment]
> @Rinary1 
> ты разве не делал блокировку на вампира для священника?

Не делал, в целом как и у генокрадов, нету ограничений

**Comment by KaiserMaus** [comment]
Я думаю что стоит, так как если вампир не палиться это единственный способ его найти
