### ISSUE TITLE
[Предложение] Работа ЭМИ на МЕХов

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#641]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
Сейчас ЭМИ любое делает Меха бесполезным сразу как только попадёт.
будь-то Крик генокрада, ИОНка или ЭМИ имплант/граната

**Опишите желаемое**
Я предлагаю сделать "энергоячейке высокой ёмкости" PowerCageHigh  иммунитет  на ЭМИ, в замен повысив ёмкость батареи Оружия Мехов с 200 до 800-1000 

Теперь при попадании в меха всё оборудование меха сядет и для использования мех будет восполнять 800-1500  заряда из ёмкости батареи.  6200 всего имеет батарея.

Всего пару попаданий ЭМИ и мех встанет без энергии, прям как сейчас после первого же воздействия
Таким Образом мех не будет садиться от любого чиха ЭМИ но и  ЭМИ Оружие и приспособления не станут бесполезными
**Основная проблема**
- Оперативники покупают Меха за 65-90ТК+Оружие до 30ТК+ а меха выносят с одного плевка в их сторону.

**Comment by VigersRay** [comment]
Проблема в числах сжигания энергии а не в самом эми, никто не балансил это.

**Comment by KaiserMaus** [comment]
Сказали костыль, по итогу сделали как говорил =3
