### ISSUE TITLE
Карта Cog\Oasis не работают

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#654]
## Описание
Карта sunrise Cog\Oasis не работают, если выиграет в голосовании или поставят вручную то не будет станции и все игроки будут гостами

**Воспроизведение**
Setmap sunrisecog

**Comment by KaiserMaus** [comment]
> Исправлено в [a242c81](https://github.com/space-sunrise/space-station-14/commit/a242c81374f32e4b7f60c2e48b3d5a4806c86005)

Какая ошибка была?

**Comment by VigersRay** [comment]
> > Исправлено в [a242c81](https://github.com/space-sunrise/space-station-14/commit/a242c81374f32e4b7f60c2e48b3d5a4806c86005)
> 
> Какая ошибка была?

![{61D1BECF-20A5-4381-96DC-19CAB03C7689}](https://github.com/user-attachments/assets/249e72a0-f0df-46b5-9f5b-29f175105c6b)
