### ISSUE TITLE
Резиновые Патроны

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#657]
## Описание
Наша сборка восстановила Резиновые Патроны но печатать такие патроны можно ТОЛЬКО в Фабрикаторе Экзокостюмов(Мехи/Борги) и нигде иначе

**Воспроизведение**
Исследовать нелетальные приспособления и открыть фаб СБ и Фабрикатор Экзокостюмов.

**Медиа**
[Снимок экрана 2024-11-16 231705](https://github.com/user-attachments/assets/d962a129-035a-457f-96d8-052637055c98)

**Comment by pxc1984** [comment]
Очень похоже на баг. Надо бы заняться этим.

**Comment by VigersRay** [comment]
> ## Описание
> Наша сборка восстановила Резиновые Патроны но печатать такие патроны можно ТОЛЬКО в Фабрикаторе Экзокостюмов(Мехи/Борги) и нигде иначе
> 
> **Воспроизведение** Исследовать нелетальные приспособления и открыть фаб СБ и Фабрикатор Экзокостюмов.
> 
> **Медиа** [Снимок экрана 2024-11-16 231705](https://github.com/user-attachments/assets/d962a129-035a-457f-96d8-052637055c98)

Еще одно сделано но не закрыто.
