### ISSUE TITLE
[Предложение] Улучшение: Телепорт Синдиката

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#658]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
"Дорого за средство твоего гиба"
Телепорт стоит 12тк и даёт возможность прыгнуть два раза. но если прыжок будет не удачный и в телепортере не будет заряда игрока гибнет.  Эта вещь убила много Агентов.
Моё улучшение повысит интерес агентам к телепортеру и будет меньше смертей, зачастую Агент проникает и уже на отходе получая ошибку его гибает из-за недостатка зарядов. 

**Опишите желаемое**
Увеличить Количество зарядов Телепорта Синдиката 2>3
Увеличить Время перезарядки 20>30

**Дополнительный контекст**

**Comment by VigersRay** [comment]
> **Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.** "Дорого за средство твоего гиба" Телепорт стоит 12тк и даёт возможность прыгнуть два раза. но если прыжок будет не удачный и в телепортере не будет заряда игрока гибнет. Эта вещь убила много Агентов. Моё улучшение повысит интерес агентам к телепортеру и будет меньше смертей, зачастую Агент проникает и уже на отходе получая ошибку его гибает из-за недостатка зарядов.
> 
> **Опишите желаемое** Увеличить Количество зарядов Телепорта Синдиката 2>3 Увеличить Время перезарядки 20>30
> 
> **Дополнительный контекст**

Ты сделал это. Зарой что-ли.
