### ISSUE TITLE
БАГ: Хиругия делает людей БЕССМЕРТНЫМИ

### ISSUE THREAD

**Issue by SplikZerys** [space-sunrise/space-station-14#660]
Если открыть рану, то человек бессмертен

**Comment by pxc1984** [comment]
Этот баг ринари исправил в патче 7e5e2031e2cd253bad910c37d1b098235156f0f3, с обновлением серверов должно исправиться.

**Comment by VigersRay** [comment]
Исправлено https://github.com/space-sunrise/space-station-14/commit/7e5e2031e2cd253bad910c37d1b098235156f0f3
