### ISSUE TITLE
Покраска Рипли и Рипли Мк2

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#662]
## Описание
Есть Рипли и Рипли Мк2

Вся краска кроме MechPaintRipleyHauler сделана для Мк2 но в игре можно покрасить только Обычный Рипли

**Медиа**
![Снимок экрана 2024-11-17 105727](https://github.com/user-attachments/assets/eb8a84ca-9994-43e6-b4fe-4d7061604bdb)
Слева Мк2 справа покрашенные обычные Рипли Мк1

**Comment by Rinary1** [comment]
потому-что в 13 нет рипли мк.II есть лишь рипли MK.II который у нас MK.II просто вырежьте ебаный MK.I, назовите его как старый как было в 13, и всё

**Comment by KaiserMaus** [comment]
> потому-что в 13 нет рипли мк.II есть лишь рипли MK.II который у нас MK.II просто вырежьте ебаный MK.I, назовите его как старый как было в 13, и всё

Если смотреть на ТГ то там есть Рипли и Рипли Мк2
Отличия у них в том что один быстрый ценой брони и без возможности ходить в космос, второй же имеет броню и закрытую капсулу

У нас просто удалить Рипли будет плохой идеей, МК2 не сильно подходит для работы грузчиком из-за своей скорости

**Comment by Rinary1** [comment]
> > потому-что в 13 нет рипли мк.II есть лишь рипли MK.II который у нас MK.II просто вырежьте ебаный MK.I, назовите его как старый как было в 13, и всё
> 
> Если смотреть на ТГ то там есть Рипли и Рипли Мк2
> Отличия у них в том что один быстрый ценой брони и без возможности ходить в космос, второй же имеет броню и закрытую капсулу
> 
> У нас просто удалить Рипли будет плохой идеей, МК2 не сильно подходит для работы грузчиком из-за своей скорости 

Ну тогда anyway пусть спрайтеры рисуют каждому Рипли свою вариацию этих красок

**Comment by VigersRay** [comment]
> > > > потому-что в 13 нет рипли мк.II есть лишь рипли MK.II который у нас MK.II просто вырежьте ебаный MK.I, назовите его как старый как было в 13, и всё
> > > 
> > > 
> > > Если смотреть на ТГ то там есть Рипли и Рипли Мк2
> > > Отличия у них в том что один быстрый ценой брони и без возможности ходить в космос, второй же имеет броню и закрытую капсулу
> > > У нас просто удалить Рипли будет плохой идеей, МК2 не сильно подходит для работы грузчиком из-за своей скорости
> > 
> > 
> > Ну тогда anyway пусть спрайтеры рисуют каждому Рипли свою вариацию этих красок
> 
> Ну будет когда нибудь, но сейчас краски сделанные для Мк2 онли подходят для мк1 Тут или дать пока что всем краскам для мехов типа Рипли возможность покраски или разрешить красить Мк2 заместо Мк1
> 
> В ТГ там вообще улучшение Рипли, то есть сначала собирать Рипли потом уже улучшать до Мк2

ты это пофиксил уже? Тогда закрой.
