### ISSUE TITLE
Vampire: Вечно голодный Вампир

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#663]
## Описание
Вампир имеет свой метаболизм ему надо пить кровь для способностей но так же он имеет Голод, самый обычный голод как у людей вот только Вампир не может есть ничего, а кровь не восстанавливает еду. 
По итогу вампир должен найти измельчитель и перемалывать себе еду чтобы выпить питательные вещества.
**Воспроизведение**
Стать вампиром, понизить голод до низких значений, попробовать скушать что-то

**Comment by Rinary1** [comment]
Не баг, фича

**Comment by KaiserMaus** [comment]
Ну тогда вампиры как Аутисты и прочие инвалиды могут есть только  в жидком виде.

**Comment by VigersRay** [comment]
> Не баг, фича

так фича или баг?

**Comment by Rinary1** [comment]
> > Не баг, фича
> 
> так фича или баг?

баг, надо добавить просто вампира в кондишены реагента uncoockedprotain

**Comment by VigersRay** [comment]
> > > Не баг, фича
> > 
> > 
> > так фича или баг?
> 
> баг, надо добавить просто вампира в кондишены реагента uncoockedprotain
![image](https://github.com/user-attachments/assets/7df1ab15-44a1-4bc8-8b79-c51eb51d43b1)
Как-бы...

**Comment by Rinary1** [comment]
Я уже исправил если что
