### ISSUE TITLE
Footprints license violation

### ISSUE THREAD

**Issue by Rinary1** [space-sunrise/space-station-14#664]
## Описание

Следы взятые из BackmenАтраксии, WWhiteDream Project, EE. Под лицензией AGPLv3. Есть вероятность что автор заметит и как с суперматерией, начнет пресовать и заставлять нацепить на себя AGPLv3 или убрать код. Кстати, автор гением был и суперматерия у оффов не под лицензией он потом ещё извенялся, хдд.

https://github.com/Rxup/space-station-14/pull/861
https://github.com/Simple-Station/Einstein-Engines/pull/1190
https://github.com/WWhiteDreamProject/wwdpublic/pull/110

**Comment by Rinary1** [comment]
> 😐

Да... Если что я не шучу, он уже писал сторисам и старлайту, там Solidus на лицензии дрочит, а потом он говорит что ненавидит лицензии) Крч там двуличный разраб и брать у ее лучше ничего не стоит

**Comment by KaiserMaus** [comment]
GitHub Drama

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
Тот кто портировал писал же что они с имперки взяты, нет?

**Comment by Rinary1** [comment]
> Тот кто портировал писал же что они с имперки взяты, нет? 

Все что было в том пр-е взято из выше указанных репо, сравните код, просто автор гений, либо в ручную либо юзая ИИ назерачил комментов и все

**Comment by Rinary1** [comment]
> > Тот кто портировал писал же что они с имперки взяты, нет? 
> 
> Все что было в том пр-е взято из выше указанных репо, сравните код, просто автор гений, либо в ручную либо юзая ИИ нахерачил комментов и все

**Comment by Rinary1** [comment]
> > > Тот кто портировал писал же что они с имперки взяты, нет?
> > 
> > Все что было в том пр-е взято из выше указанных репо, сравните код, просто автор гений, либо в ручную либо юзая ИИ нахерачил комментов и все
> 
> А что насчёт тогда системы настроения? (Mood) Она же тоже вроде взята из EE

Если она тоже оттуда, она под той же лицензией

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
> Или я путаю что-то

Ну смотря на видео демонстрацию в пре ee, скорее всего

**Comment by kanopus952** [comment]
@rhailrake вопросик. А зачем ты портировал системы под лицензией?

**Comment by Rinary1** [comment]
> @rhailrake вопросик. А зачем ты портировал системы под лицензией? 

Он думал что судиться будут по РФ законам, но ее сделали ход конем и могут блокнуть гитхаб санрайза

**Comment by rhailrake** [comment]
Вопросики закрыты.
Код взят с frosty-dev, зачем что-то говорить если вы не знаете. Разрешение есть.
![image](https://github.com/user-attachments/assets/61298544-ef22-4a5b-87e7-731702946cc3)

**Comment by rhailrake** [comment]
Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.

**Comment by Rinary1** [comment]
> Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО. 

Frosty dev под MIT, ну так если код взят из него, нахуя было устраивать клоунаду, приглашать типа в РФ чтобы судиться и делать PR где лицензию удаляешь?

**Comment by DVOniksWyvern** [comment]
> Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.

В данном случае, речи о WWDP не идёт, не знаю зачем ты нас приплёл, это код с Бэкмена - и если он был переписан и релицензирован, то он уже по факту не является тем же самым кодом, что на старой ВДшной репе хранится. Следовательно, пищат о нелегальности немного глупо, считая что против копирайта воюешь ты.

Если ты еще за порты деньги берешь, то мне кажется, тебе стоило бы вернуть эти деньги, а то как-то нечестно получается. Хотя свои 50к, которые ты у меня угнал, я так и не получил - но да ладно, не об этом речь.

**Comment by rhailrake** [comment]
> > Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.
> 
> Frosty dev под MIT, ну так если код взят из него, нахуя было устраивать клоунаду, приглашать типа в РФ чтобы судиться и делать PR где лицензию удаляешь?
> 
> * Не вижу на frosty dev системы настроения

![image](https://github.com/user-attachments/assets/a84f2c93-ca1f-4dfa-aee9-44a054ca97a5)
helloyyy

**Comment by rhailrake** [comment]
> > Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.
> 
> В данном случае, речи о WWDP не идёт, не знаю зачем ты нас приплёл, это код с Бэкмена - и если он был переписан и релицензирован, то он уже по факту не является тем же самым кодом, что на старой ВДшной репе хранится. Следовательно, пищать о нелегальности немного глупо, считая что против копирайта воюешь ты - и нарушаешь его сам же.
> 
> Если ты еще за порты деньги берешь, то мне кажется, тебе стоило бы вернуть эти деньги, а то как-то нечестно получается. Хотя мои 50к, которые ты у меня угнал, я так и не получил - но да ладно, не об этом речь.

Переписан полные штаны(портирован 1 в 1)

**Comment by rhailrake** [comment]
> > Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.
> 
> Frosty dev под MIT, ну так если код взят из него, нахуя было устраивать клоунаду, приглашать типа в РФ чтобы судиться и делать PR где лицензию удаляешь?
> 
> * Не вижу на frosty dev системы настроения

Frosty-dev не под мит, там есть клозед-сурс репы под proprietary license.

**Comment by Rinary1** [comment]
> > > Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.
> > 
> > Frosty dev под MIT, ну так если код взят из него, нахуя было устраивать клоунаду, приглашать типа в РФ чтобы судиться и делать PR где лицензию удаляешь?
> > 
> > * Не вижу на frosty dev системы настроения
> 
> Frosty-dev не под мит, там есть клозед-сурс репы под proprietary license.

Именно архивированный репо где есть следы, под мит

**Comment by rhailrake** [comment]
> > > > Еще раз повторяю, код на WWDP спизжен с frosty-dev НЕЛЕГАЛЬНО.
> > > 
> > > 
> > > Frosty dev под MIT, ну так если код взят из него, нахуя было устраивать клоунаду, приглашать типа в РФ чтобы судиться и делать PR где лицензию удаляешь?
> > > 
> > > * Не вижу на frosty dev системы настроения
> > 
> > 
> > Frosty-dev не под мит, там есть клозед-сурс репы под proprietary license.
> 
> Именно архивированный репо где есть следы, под мит

Причем тут мит и архивированная репа? Там нету следов, если я не прав дай ссылку.
