### ISSUE TITLE
БАГ: EvilTwin/Fugitive игра не спавнит 

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#665]
## Описание
Ни злой двойник ни Беглец не спавнятся игрой,только через addgamerule можно их добавь.

**Comment by VigersRay** [comment]
Исправил https://github.com/space-sunrise/space-station-14/commit/1c055423825fcd131a106d2cc0b853f4cd7bf3ca

На самом деле игра их спавнила, баг был в другом, оффы добавили групировку по ролям но забили хуй на поддержку ролей с требованиями, из-за чего больше половины гост ролей не отображалось в списке призраков. (При этом в счетчике их было много а в списке мало)
