### ISSUE TITLE
Vampire: обычные Госты видят icon Вампира

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#666]
## Описание
обычные Госты видят icon Вампира хотя должны только Агосты

**Воспроизведение**
Выдать/найти Вампира и войти в гост

**Медиа**
![Снимок экрана 2024-11-18 150209](https://github.com/user-attachments/assets/f56ec4ea-0563-4bf1-bd83-5925eccdf054)

**Comment by Nrd-K** [comment]
Обычные госты и нулевых видят, ну или видели, не знаю исправлял это кто-то или нет

**Comment by Rinary1** [comment]
> > Обычные госты и нулевых видят, ну или видели, не знаю исправлял это кто-то или нет
> 
> ![Снимок экрана 2024-11-18 153551](https://private-user-images.githubusercontent.com/181247406/387285905-6558417d-a83e-4fc2-a02c-4bd7590bac15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjk1NTAsIm5iZiI6MTczMjAyOTI1MCwicGF0aCI6Ii8xODEyNDc0MDYvMzg3Mjg1OTA1LTY1NTg0MTdkLWE4M2UtNGZjMi1hMDJjLTRiZDc1OTBiYWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNTE0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmMyNDM4ODk5ODc0YzU1MTk5YzhmNzQ1YmFlZjQzMzBjY2E1YTg5NmY4YzM0MDU0ZGFlMjIyZmI0M2IzMTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.otESNiG1GVx3liC87dEfLgau01Fj0RF3R-g5Li8FZ70) Да видят, но не думаю что это критично как за игре за вампира, зомба быстрый режим где уже с 5-20 минут раунда начинается резня.

генокрадов тоже видно

**Comment by VigersRay** [comment]
> > > Обычные госты и нулевых видят, ну или видели, не знаю исправлял это кто-то или нет
> > 
> > 
> > ![Снимок экрана 2024-11-18 153551](https://private-user-images.githubusercontent.com/181247406/387285905-6558417d-a83e-4fc2-a02c-4bd7590bac15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjk1NTAsIm5iZiI6MTczMjAyOTI1MCwicGF0aCI6Ii8xODEyNDc0MDYvMzg3Mjg1OTA1LTY1NTg0MTdkLWE4M2UtNGZjMi1hMDJjLTRiZDc1OTBiYWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNTE0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmMyNDM4ODk5ODc0YzU1MTk5YzhmNzQ1YmFlZjQzMzBjY2E1YTg5NmY4YzM0MDU0ZGFlMjIyZmI0M2IzMTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.otESNiG1GVx3liC87dEfLgau01Fj0RF3R-g5Li8FZ70) Да видят, но не думаю что это критично как за игре за вампира, зомба быстрый режим где уже с 5-20 минут раунда начинается резня.
> 
> генокрадов тоже видно

Видно потому что автор говнокодер. Зомби ведь не видно нулевых. 
Ты это у себя чинил? Если да то кинь фикс. И надо бы генокрадов починить.

**Comment by Rinary1** [comment]
> > > > Обычные госты и нулевых видят, ну или видели, не знаю исправлял это кто-то или нет
> > > 
> > > 
> > > ![Снимок экрана 2024-11-18 153551](https://private-user-images.githubusercontent.com/181247406/387285905-6558417d-a83e-4fc2-a02c-4bd7590bac15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjk1NTAsIm5iZiI6MTczMjAyOTI1MCwicGF0aCI6Ii8xODEyNDc0MDYvMzg3Mjg1OTA1LTY1NTg0MTdkLWE4M2UtNGZjMi1hMDJjLTRiZDc1OTBiYWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNTE0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmMyNDM4ODk5ODc0YzU1MTk5YzhmNzQ1YmFlZjQzMzBjY2E1YTg5NmY4YzM0MDU0ZGFlMjIyZmI0M2IzMTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.otESNiG1GVx3liC87dEfLgau01Fj0RF3R-g5Li8FZ70) Да видят, но не думаю что это критично как за игре за вампира, зомба быстрый режим где уже с 5-20 минут раунда начинается резня.
> > 
> > 
> > генокрадов тоже видно
> 
> Видно потому что автор говнокодер. Зомби ведь не видно нулевых. Ты это у себя чинил? Если да то кинь фикс. И надо бы генокрадов починить.

я не чинил, весь фикс это убрать в прототипе 1 строчку...

**Comment by VigersRay** [comment]
> > > > > Обычные госты и нулевых видят, ну или видели, не знаю исправлял это кто-то или нет
> > > > 
> > > > 
> > > > ![Снимок экрана 2024-11-18 153551](https://private-user-images.githubusercontent.com/181247406/387285905-6558417d-a83e-4fc2-a02c-4bd7590bac15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjk1NTAsIm5iZiI6MTczMjAyOTI1MCwicGF0aCI6Ii8xODEyNDc0MDYvMzg3Mjg1OTA1LTY1NTg0MTdkLWE4M2UtNGZjMi1hMDJjLTRiZDc1OTBiYWMxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQxNTE0MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmMyNDM4ODk5ODc0YzU1MTk5YzhmNzQ1YmFlZjQzMzBjY2E1YTg5NmY4YzM0MDU0ZGFlMjIyZmI0M2IzMTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.otESNiG1GVx3liC87dEfLgau01Fj0RF3R-g5Li8FZ70) Да видят, но не думаю что это критично как за игре за вампира, зомба быстрый режим где уже с 5-20 минут раунда начинается резня.
> > > 
> > > 
> > > генокрадов тоже видно
> > 
> > 
> > Видно потому что автор говнокодер. Зомби ведь не видно нулевых. Ты это у себя чинил? Если да то кинь фикс. И надо бы генокрадов починить.
> 
> я не чинил, весь фикс это убрать в прототипе 1 строчку...

скажи какую, лень разбираться

**Comment by VigersRay** [comment]
решено
