### ISSUE TITLE
[Предложение] Убрать бесконечный бег, поменять местами ходьбу и бег.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#681]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**

В сравнении с сс13 в игре слишком высокая динамика из-за слишком огромной скорости передвижения.
Без понятия зачем оффы сделали стандартную скорость такой огромной и почему по умолчанию бег а ходьба на шифт.
Высокая скорость передвижения сильно влияет на уровень рп, а так же весьма в некотором смысле влияет на производительность сервера и клиента (чем больше физических обьектиков которые двигаются с большой скоростью тем больше нагрузка на MoverController. А для клиента чем быстрее он движется тем быстрее нужно прогружать PVS что тоже заметно влияет на производительность.)
Однако очевидно что все игроки привыкли к этой динамике бесконечного бега по станции, но попытаться это исправить стоит.
План в целом таков:
- Для всех по умолчанию будет установлена ходьба, на шифт бег. Так во многих играть так что адаптироваться будет не сложно, да и меньше людей будет ездить на бананах клуни.
- Бег будет ограничен стаминой, примерно 1 минута беспрерывного бега. Не уверен стоит ли подвязывать эту стамину к той что отвечает за оглушение, но можно поэкспериментировать.
- Параметр за переключение кнопки шифт в настройках удалить.

В целом это должно будет снизить как и нагрузку при 100+ игроках, так и сделать игру более плавной.
Если игроки будут сильно бухтеть попробуем сделать это цваром и включать только на ореоле.
Но тогда будет очевидно ясно - игроки санрайза хотят экшена с малей долей РП а не душных СРП правил и таблиц навыков.

**Опишите желаемое**

**Дополнительный контекст**

**Comment by VigersRay** [comment]
> Может постепенно снижать скорость? Сейчас бег слишком быстрый для игры а шаг слишком медленный (2.5) может начать с 3.5 шагом?

ходьба быстрее 3 вызывает подскальзывание

**Comment by KaiserMaus** [comment]
> > Может постепенно снижать скорость? Сейчас бег слишком быстрый для игры а шаг слишком медленный (2.5) может начать с 3.5 шагом?
> 
> ходьба быстрее 3 вызывает подскальзывание

2.9?

**Comment by mithail** [comment]
Мне нравки

**Comment by kanopus952** [comment]
Определенно нужно. Хотя бы в качестве эксперимента.

**Comment by KaiserMaus** [comment]
> > Может постепенно снижать скорость? Сейчас бег слишком быстрый для игры а шаг слишком медленный (2.5) может начать с 3.5 шагом?
> 
> ходьба быстрее 3 вызывает подскальзывание

Может добавить всему дальнему оружию при двуручном хвате замедление от 5 до 30%? 
Динамику боя точно понизит а так же сделает нишу для более легкого оружия, легкие слабые ПП, Пистолеты и так далее.
Может даже щиты будут использовать чаще чем никогда
Такая механика есть на Маринах в 13 точно
