### ISSUE TITLE
Борги могут наливать содержимое бесконечного гипоспрея в сосуды. 

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#684]
## Описание

Абуз, нужно разрешить колоть только в сущность. 
Особенно касается мед борга синди с омнизином.

**Воспроизведение**

**Медиа**

**Дополнительный контекст**

**Comment by kanopus952** [comment]
Эт вроде легко, чуть дописать компонент гипоспрея и добавить что-то вроде borghypo: false/true, который будет отвечать за проверку скажем HumanoidApperance

**Comment by kanopus952** [comment]
А, так в гипо уже есть такой бул. Короче сделаю

**Comment by VigersRay** [comment]
Исправлено
