### ISSUE TITLE
Снова все сломалось на борге.

### ISSUE THREAD

**Issue by W1mHack** [space-sunrise/space-station-14#686]
## Описание
 EchoVRC Можете перехватить контроль и потестить  Не работает сканер Не работает мед Не работает перетаскивание персов на кровать  (видео можно на середину мотать)

**Воспроизведение**

**Медиа**
<!-https://discord.com/channels/1174575355370160190/1188705209615122523/1309153105845293106->

**Дополнительный контекст**

**Comment by VigersRay** [comment]
Исправлено
