### ISSUE TITLE
Снаряжение кадетов

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#696]
## Описание

У кадетов есть табельное и пояс, что немного нарушает логику их роли, и сильно мешает в режиме Яо когда через 5 минут после смерти игроки заходят за кадетов.
В целом думаю стоит убрать их снарягу, включая нож.

**Воспроизведение**

**Медиа**

**Дополнительный контекст**

**Comment by KaiserMaus** [comment]
Кадет так же имеет простенький стандартный Бронежилет на 30%
По поводу Ножам, его можно как раз таки и оставить, так как в бриге нет возможности получить новый (СБ тех имеет всего 2). 
Пояс с принадлежностями и табельное можно убрать спокойно так как в бриге в шкафах Офицеров есть пояса а в Оружейной есть дополнительные Пистолеты

**Comment by VigersRay** [comment]
Исправлено
