### ISSUE TITLE
[Предложение] Вернуть/добавить роль Патологоанатома

### ISSUE THREAD

**Issue by W1mHack** [space-sunrise/space-station-14#700]
Может быть пора его уже добавлять/возвращать в игру? Страничка на Вики по нему существует давно, из особого снаряжения ему нужна только печать. Через костыли уже делала данную роль, в целом, довольно играбельная, данная роль бы могла бы повысить эффективность работы мед отдела, вместе с развитием хирургии, можно было бы добавить и к данной роли какие-то механы, чтобы узнавать причину смерти (но и без этого отдельный человек для морга был бы неплох).

**Comment by VigersRay** [comment]
> done

опять прав нету?

**Comment by VigersRay** [comment]
Реализовано
