### ISSUE TITLE
Жало генокрада на смену расы.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#710]
## Описание

Абсолютно отвратительный навык генокрада в реаллиях сс13, вырезать нужно обязательно.

**Воспроизведение**

**Медиа**

**Дополнительный контекст**

**Comment by KaiserMaus** [comment]
Пока что просто Грифозный навык, если бы он на время менял было бы лучше.  Как например с жалом на фейк руку Клинок.

**Comment by VigersRay** [comment]
Исправлено https://github.com/space-sunrise/space-station-14/commit/838b0ff8e3e10a73651781822b3f51417b84668e
