### ISSUE TITLE
[Предложение] Звуковое оповещение повяление новой роли для призраков.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#721]
Призраки часто пропускают роли ибо у них окно закрыто. Да и так было в сс13 так что как бы да

**Comment by VigersRay** [comment]
Решено https://github.com/space-sunrise/space-station-14/commit/dbfa90e95678e7e593e6e25bc6085de47b4dde47

**Comment by KaiserMaus** [comment]
Нужно доделывать, разделить на условные мидраунд антаг роли и просто роли и дать возможность оставить в настройках что надо
сейчас улитка или пИИ появляется в выборе и играет звук.
Кому реально интересна улитка? они обычно и так всю смену доступны
