### ISSUE TITLE
Нарушение лицензии AGPL - система лежания и телескоп

### ISSUE THREAD

**Issue by DVOniksWyvern** [space-sunrise/space-station-14#725]
## Описание

Я являюсь владельцем репозитория WWDPublic : https://github.com/WWhiteDreamProject/wwdpublic
Я являюсь прожект менеджером организации WWhiteDreamProject.

Дальнейший текст является публичным постом который был сделан пост-фактум, мы уже связались с Гитхабом и получили подтверждение, что владельцам Санрайза было сообщено о нарушении и что в течении какого-то времени, код будет удалён либо владельцами, либо самим гитхабом.

Коммит, который нарушает лицензию: https://github.com/space-sunrise/space-station-14/commit/40568a243c8389d10bb278516b3e78a0d3290591#diff-8d45b12b199605c5a05fcec64515f187943b6397f29b4369ea6a6e218479dd3d

Файлы:
Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
Content.Shared/Standing/SharedLayingDownSystem.cs
Content.Shared/Standing/StandingStateSystem.cs
Content.Server/Standing/LayingDownSystem.cs
Content.Client/Standing/LayingDownSystem.cs

Оригинал: https://github.com/WWhiteDreamProject/wwdpublic/pull/2/files

Content.Client/Telescope/TelescopeSystem.cs
Content.Shared/Telescope/SharedTelescopeSystem.cs
Content.Shared/Telescope/TelescopeComponent.cs

Оригинал: https://github.com/WWhiteDreamProject/wwdpublic/pull/8/files

В принципе, советую чтобы любой код от товарища @rhailrake вам следовало бы проверить и превентивно убрать из репозитория.

**Comment by rhailrake** [comment]
Прекратите делать ложные заявления об авторских правах. Вы прекрасно знаете, что этот код изначально не ваш, а был взят вами из другого репозитория. Ложные DMCA жалобы являются нарушением закона. Если у вас есть реальные претензии - решайте их через юридические каналы, а не через публичные обвинения. До завершения рассмотрения встречного DMCA уведомления репозиторий продолжит работу согласно правилам GitHub.

**Comment by rhailrake** [comment]
![image](https://github.com/user-attachments/assets/af29f876-74e4-4e98-96be-076100770308)

**Comment by Valtosin** [comment]
отказано

**Comment by DVOniksWyvern** [comment]
> Вы прекрасно знаете, что этот код изначально не ваш, а был взят вами из другого репозитория. 

1) Код систем был релицензирован оригинальным автором - Spatison'ом.
2) Код систем был переписан для успешного портирования на новую базу.
3) Код систем был перенесён на Санрайз без указания авторства, оригинального репозитория и так далее.

Вкупе, всё это означает, что код по сути, "новый" и то, что в прошлом Spatison написал ту же самую систему для Вайт Дрима до развала - не означает, что у вас теперь есть права на код нового Вайт Дрима, от этого вы сами отказались.

Публично это выносится для того, чтобы остальные члены сообщества могли самостоятельно оценить твою неблагонадёжность и отсуствие этики, очевидно, что вопрос легальности/лицензии будет решён за пределами чатов.

Не мешает мне еще раз напомнить, что если ты берешь за эти порты деньги, то тебе следовало бы вернуть их самостоятельно, хотя про ту историю с 50к рублей, которые ты взял у меня на разработку хирургии и с которыми убежал - я не устану вспоминать.

**Comment by rhailrake** [comment]
> > Вы прекрасно знаете, что этот код изначально не ваш, а был взят вами из другого репозитория.
> 
> 1. Код систем был релицензирован оригинальным автором - Spatison'ом.
> 2. Код систем был переписан для успешного портирования на новую базу.
> 3. Код систем был перенесён на Санрайз без указания авторства, оригинального репозитория и так далее.
> 
> Вкупе, всё это означает, что код по сути, "новый" и то, что в прошлом Spatison написал ту же самую систему для Вайт Дрима до развала - не означает, что у вас теперь есть права на код нового Вайт Дрима, от этого вы сами отказались.
> 
> Публично это выносится для того, чтобы остальные члены сообщества могли самостоятельно оценить твою неблагонадёжность и отсуствие этики, очевидно, что вопрос легальности/лицензии будет решён за пределами чатов.
> 
> Не мешает мне еще раз напомнить, что если ты берешь за эти порты деньги, то тебе следовало бы вернуть их самостоятельно, хотя про ту историю с 50к рублей, которые ты взял у меня на разработку хирургии и с которыми убежал - я не устану вспоминать.

Не мешает мне еще раз напомнить, хватит пиздить код с валеро-вайта.
Ты не можешь рецензировать код по взмаху руки, на тот момент код был под proprietary license.
Хотя зачем объяснять ты и так знаешь.

**Comment by rhailrake** [comment]
Твои претензии по поводу лицензий абсолютно беспочвенны, и мы оба это знаем. 
Насчёт денег - это вообще смешно. Ты сам прекрасно помнишь, как всё было на самом деле. Хватит передергивать факты и пытаться манипулировать общественным мнением.
Раз уж ты так уверен в своей правоте - дождись официального ответа от GitHub. А пока прекрати этот цирк с публичными обвинениями. Это "непрофессионально и только роняет твою репутацию". Раз за этику решил поговорить.

**Comment by DVOniksWyvern** [comment]
> Насчёт денег - это вообще смешно. Ты сам прекрасно помнишь, как всё было на самом деле. Хватит передергивать факты и пытаться манипулировать общественным мнением.

Да, я помню как ты просил меня убрать новость о том, что ты стащил деньги и пытался сделать вид, что "я не знаю на что ты донатил", в то время как какой-то донатер с ВД, я честно не вспомню на ходу ник, так-же "задонатил" тебе 40к. И еще потом было 5к за то, чтобы ты залил в репу телепортер с начала раунда какому-то пареньку.

Не пытайся в дэмедж контроль, у тебя он не получается. Если надо - я вытащу абсолютно все логи, скриншоты, расписки и так далее, и они будут лежать здесь для того, чтобы моё "передёргивание" фактов подкрепить.

![image](https://github.com/user-attachments/assets/9f361b6a-f717-4d93-ab92-f3b5784da675)

Ну и касательно профессионализма и репутации. "Цирк" он потому, что смешной всем участникам - естественно, но это всё ещё означает, что своими действиями, направленными на "поржать" ты поставил под угрозу репозиторий третьих лиц - и в дальнейшем, если ты продолжишь, это пойдет дальше к визденам. Очевидно, что гитхаб подрежет вам эти кусочки кода, там всё понятно, но зная, что это продолжится и что ты не успокоишься, пока тебе свыше не прилетит - ты даешь ой как много возможностей недоброжелателям. 

Просто прими как факт - вы начали это, провалив свой ДМЦА на вики, мы закончим это.
