### ISSUE TITLE
[Предложение] Портативная консоль атмосферных угроз всем инженерам и атмосам.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#728]
Оффы наверное знатно бы посмеялись с такого, но наши игроки явно имеют проблемы с навыком (так называемый skill issue).
Это должно минимально повысить эффективность устранения разгерм.
Так же стоит добавить звуковое оповещение раз в 5с для всех мониторов если на станции есть разгерма.

Ещё эта консоль надо инж боргам.

**Comment by KaiserMaus** [comment]
Думаю стоит дать только Атмосам и СИ

Инженеры спокойно могут обойтись Консолью которая уже есть и стоит во многих местах

**Comment by VigersRay** [comment]
> Думаю стоит дать только Атмосам и СИ
> 
> Инженеры спокойно могут обойтись Консолью которая уже есть и стоит во многих местах

Бред, ею никто не пользуется, про неё никто не знает. Такое чуство как будто ты играешь не на санрайзе а на другом сервере. Инженеры никогда не проверяют это консоль и не будут пока у них она не появится в кармане. Игроки банально не читают чейнжлоги.

**Comment by VigersRay** [comment]
> Ну хорошо, будет портативка, есть портативные криминальные записи, по итогу юзает смотритель или ГСБ почти никогда.

Ну это потому что СБшникам проще хуярить всех чем тех у кого есть пометка розыск.

**Comment by pxc1984** [comment]
Берусь

**Comment by VigersRay** [comment]
> Берусь

У тебя прав закрывать нету?

**Comment by VigersRay** [comment]
Реализовано
