### ISSUE TITLE
Новая цель синдиката: подстава

### ISSUE THREAD

**Issue by pxc1984** [space-sunrise/space-station-14#750]
**Опишите желаемое**

Добавить новую цель синдикату: подставить случайного сотрудника. Цель будет считаться выполненной если жертва в конце смены была арестованной и живой.

**Дополнительный контекст**

https://discord.com/channels/1253315855731916821/1312597241583636573

**Comment by Xden12** [comment]
А не легче будет просто его убить?

**Comment by pxc1984** [comment]
> А не легче будет просто его убить?

Хм.. А сделаю чтоб надо было именно арестованной, но живой

**Comment by AverageNotDoingAnythingEnjoyer** [comment]
...а это разве не то же самое что убить или не дать сбежать?
