### ISSUE TITLE
[Предложение] Проблема отражения.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#758]
Фикс оффов с тем что для отражения нужно стоять на месте это конечно хорошо но работает он через задницу. Нужно убрать отражение если предмет который отражает находится не в активной руке.

**Comment by KaiserMaus** [comment]
У Оффов рефлект же работает от скорости,типо чем быстрее бегает перс тем меньше рефлекта. разве не так?

**Comment by VigersRay** [comment]
> У Оффов рефлект же работает от скорости,типо чем быстрее бегает перс тем меньше рефлекта. разве не так?

Скажи это учёному в ботинках на 150 скорости который отражает всё и вся.
В целом какая разница если ты можешь засунуть в карман даблу и она будет отражать.
