### ISSUE TITLE
[Баг] Плутонивое ядро наносит урон даже в защитном ящике синдиката.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#761]
Ну как бы всё очевидно по теме.

**Comment by KaiserMaus** [comment]
Ящик снижает рациацию но примерно с 6>4

**Comment by VigersRay** [comment]
Исправлено https://github.com/space-sunrise/space-station-14/commit/2866de91deb00a15c016692583b1974b4b6bce36
