### ISSUE TITLE
[Issue] Нет фильтра для имени и фамилии

### ISSUE THREAD

**Issue by Esco-dev** [space-sunrise/space-station-14#804]
## Описание

Нет фильтра для имени и фамилии. Туда можно вставить почти что угодно.

**Воспроизведение**

Написание любой несуразицы в графу имени и фамилии

**Медиа**

Не требуется.

**Дополнительный контекст**

Ну ибо зачем.

**Comment by VigersRay** [comment]
> ## Описание
> Нет фильтра для имени и фамилии. Туда можно вставить почти что угодно.
> 
> **Воспроизведение**
> 
> Написание любой несуразицы в графу имени и фамилии
> 
> **Медиа**
> 
> Не требуется.
> 
> **Дополнительный контекст**
> 
> Ну ибо зачем.

Фильтр есть. На этом в целом закрыто.

**Comment by VigersRay** [comment]
![image](https://github.com/user-attachments/assets/b4bd24c9-d456-4e90-81c9-2fc9a0c9c292)

**Comment by VigersRay** [comment]
Если есть КОНКРЕТНЫЕ предложения по изменению фильтра - так и пиши.
