### ISSUE TITLE
Обновить Вампиров взяв обновление от ss14Starlight (Rinary)

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#810]
## Описание

**Воспроизведение**

**Медиа**

**Дополнительный контекст**
(https://github.com/ss14Starlight/space-station-14/commits/4980c409adaaba5a87091a082bdf0d7332099dee/Content.Server/Vampire)

**Comment by VigersRay** [comment]
> ## Описание
> **Воспроизведение**
> 
> **Медиа**
> 
> **Дополнительный контекст** (https://github.com/ss14Starlight/space-station-14/commits/4980c409adaaba5a87091a082bdf0d7332099dee/Content.Server/Vampire)

а не проще это сделать самому ринари? Дело 5 минут, попроси его, просто если другой чел начнет переносить то это багов будет милион так как он забудет какой-то кусок
