### ISSUE TITLE
[Баг] Джоб-баны на антагонистов

### ISSUE THREAD

**Issue by Perl404** [space-sunrise/space-station-14#824]
## Описание
Если Модератор выдаёт джоб-бан на антагонистов то он выдаётся только на Job:PlanetPrisoner, а остальные антагонисты не блокируются и так же могут свободно выпадать у игрока

**Воспроизведение**
banpanel - Бан роли - вся категория Antagonist или же любой другой антагонист - выдача бана - портал модерации - role bans - смотрим на выданный бан и видим только Job:PlanetPrisoner(в вебхуке Discord проблем нет и там показывается что якобы были забанены все антагонисты)

**Медиа**
![image](https://github.com/user-attachments/assets/b2285c98-b2b1-4636-9227-4825cd712ff8)
![image](https://github.com/user-attachments/assets/052f273c-b0f5-4e34-bde5-7ac989e9e6c2)

**Дополнительный контекст**
Данная проблема существует уже давно и у модерации нет других путей по бану антагонистов(кроме ручного бана всех на сайте)

**Comment by VigersRay** [comment]
![image](https://github.com/user-attachments/assets/44b69f06-eb53-4c1e-8099-4e5d5ec54a12)
Это буквально не баг, в коде просто напросто нету возможности банить антагов, банятся только джоб роли.

**Comment by VigersRay** [comment]
Да, банов на антагов никогда и не существовали. А бан на зека выдается потому что есть айди джобка с таким айди как у антага.
