### ISSUE TITLE
[Баг] Задача на Кражу Мультифаз ОСЩа не выдается игрой

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#839]
## Описание

Посмотрев в коде увидел что оказывается у нас есть свои новые цели для Антагов, Украсть Мультифаз ОСЩа. Дефибрилятор ГВ но этого нет в игре. 

**Воспроизведение**

**Медиа**

**Дополнительный контекст**

**Comment by VigersRay** [comment]
Исправил
