### ISSUE TITLE
[Баг] СБ боргов видимо можно емагнуть, что странно.

### ISSUE THREAD

**Issue by Kinar7** [space-sunrise/space-station-14#843]
## Описание
Я где-то то ли на дискорде Луста, то ли на Санрайзе видел обсуждение, где упоминалось и подтверждался факт того, что игроки с помощью ЕМАГа взламывали СБ боргов. Я нахожу это странным, так-как Боевого СБ борга емагнуть нельзя. 
**Воспроизведение**
Емагнуть СБ борга.

**Comment by VigersRay** [comment]
Исправил
