### ISSUE TITLE
ПНВ космического ниндзи.

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#853]
Маска космического ниндзи не имеет ПНВ, хотя должна.

**Comment by KaiserMaus** [comment]
Должны же очки иметь такой функционал, разве нет?

**Comment by VigersRay** [comment]
> Должны же очки иметь такой функционал, разве нет?

не ебу что, знаю что чет должно

**Comment by KaiserMaus** [comment]
В общем у него очки буквально стилизированы под ПНВ

**Comment by VigersRay** [comment]
> В общем у него очки буквально стилизированы под ПНВ

Это визор а не пнв

**Comment by VigersRay** [comment]
пофиксил
