### ISSUE TITLE
[Предложение] Вернуть ГП МШ

### ISSUE THREAD

**Issue by Esco-dev** [space-sunrise/space-station-14#860]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**

Нужно вернуть ГП МШ обратно.
**Опишите желаемое**

Ну типо вы серьёзно даёте почти ФД антагам? Верните гп МШ.
**Дополнительный контекст**

**Comment by KaiserMaus** [comment]
Смотря какой билд, на некоторых ГП без мщ

**Comment by RaMbUt878** [comment]
нахой надо, пр только час назад вышел, вы его ещё не затестили толком, а уже чё-то ноете...

**Comment by RaMbUt878** [comment]
> задумайся блять

Напомню, у нас есть ОСЩ, который тоже хуйнёй мается с такими доступами, так ещё и с раундстарт леталом

**Comment by W1mHack** [comment]
ПР и так уже откатят, Главы не будут Антагами, по крайней мере в ближайшее время

**Comment by RaMbUt878** [comment]
> ПР и так уже откатят, Главы не будут Антагами, по крайней мере в ближайшее время

Вигерс ещё жестче делает, так что, никаких откатов, как я думаю впринципе.

**Comment by W1mHack** [comment]
Я б так не утверждала, после слов Сплика

**Comment by W1mHack** [comment]
Весь Кураторский состав, почти единогласно, против данного ПРа. В том числе и Сплик.

**Comment by mithail** [comment]
> ПР и так уже откатят, Главы не будут Антагами, по крайней мере в ближайшее время

Я че зря в посте указывал об удаление МШ у глав? Какой то развод получился
![389487164-55ca39ed-92aa-4063-bdbe-8d97876faeac (1)](https://github.com/user-attachments/assets/d844a720-3d55-4e17-8292-d61345494454)

**Comment by VigersRay** [comment]
Решено
