### ISSUE TITLE
Багоюз бебеплинка

### ISSUE THREAD

**Issue by VigersRay** [space-sunrise/space-station-14#869]
Заметил что разные должности дают свои бебеплинки другим должностям и просят купить у них вещи там.
Фильтр в бебеплинках привязан как раз к должности как аплинки агентов.
Как итог условный ученый просит в каждом раунде у инженера купить ему продвинутые инструменты.

**Comment by Kinar7** [comment]
Я нахожу это чем-то милым. 
Игроки доверяются друг-другу и помогают с этой казалось бы маленькой проблемой. Да и если исправить это, чувствую что будет волна негатива.

**Comment by KaiserMaus** [comment]
Просто убрать челюсти от туда вместе с экспериментальной сваркой и будет достаточно 
Сварку можно на продвинутую промышленную заменить 
А челюсти уж потерпят, бесплатный доступ в отделы жирно раундстартом, особенно если учитывать что игроки не шибко то и часто изучают рнд до этой технологии

**Comment by VigersRay** [comment]
По сути решил
