### ISSUE TITLE
[Предложение] Сделать автоматическую выдачу доступов в зависимости от кода

### ISSUE THREAD

**Issue by kanopus952** [space-sunrise/space-station-14#906]
**Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**

СБ приходится стоять в очередях за доступами, так они их ещё и не отдают после понижения кода
**Опишите желаемое**

Выдавать доступы СБ и ОСЩ автоматически в зависимости от кода на станции
**Дополнительный контекст**

**Comment by VigersRay** [comment]
> **Ваш запрос функции связан с проблемой/ошибкой? Опишите, пожалуйста.**
> 
> СБ приходится стоять в очередях за доступами, так они их ещё и не отдают после понижения кода **Опишите желаемое**
> 
> Выдавать доступы СБ и ОСЩ автоматически в зависимости от кода на станции **Дополнительный контекст**

дубль https://github.com/space-sunrise/space-station-14/issues/727
