### ISSUE TITLE
Прыжки под пивом

### ISSUE THREAD

**Issue by Losped228** [space-sunrise/space-station-14#921]
Так-с, буду краток - УДАЛИТЬ НАХУЙ ЕБАНЫЕ ПРЫЖКИ.
Почему? потому что это ебаное сырое дерьмо, ты просто можешь прыгать через стены и лишаешься коллизии, просто можешь как ебаный Нео прыгнуть и увернутся от пуль, я вообще не понимаю, как можно было добавить настолько  критически багованную хуйню, типа вы даже не тестировали? или как можно было не увидеть то, что ты просто если подойдешь к стене и прыгнешь, то тебя перекинет через стеночку.

Хотя, решить проблему можно - удалить критические баги, а так же сделать большое КД на прыжок, секунд 5.

**Comment by Losped228** [comment]
Ну типа чел реально написал и даже не зашел в игру протестировать свое чудо и увидеть настолько очевидные баги))) Почему я уже должен возвышать типа только за то, что он пишет код, даже не удостоившись его протестировать уделив на это 2-3 минуты?

По твоей логике если тип пишет код, то я должен его уважать уже просто за это? и плевать на то, что код просто ебаное халтурное дерьмо, которое он решил даже не проверять?

https://github.com/user-attachments/assets/8bc561cc-83db-4447-a0b9-4de20a0aef24

баг на столько очевидный и лежит на поверхности, что я решил даже не скидывать фрагмент с ним, но если это требуется...

**Comment by rhailrake** [comment]
> Не всегда баги очевидны. Просто наш хост думает что система:
> 
>     * Хост
> 
>     * Ведущий разраб
> 
>     * Разраб
> 
>     * Прототипер
> 
> 
> Работает хорошо. Он не задумывается что по хорошему должны быть помимо Ведущего Разработчика **мейнтейнеры** которые будут отсеивать щиткод такого рода и **QA** которые будут тестить каждый новый механ перед обновой.

это вигерс написал, как проснется исправит, видимо забыл протестить

**Comment by rhailrake** [comment]
> > > Не всегда баги очевидны. Просто наш хост думает что система:
> > > ```
> > > * Хост
> > > 
> > > * Ведущий разраб
> > > 
> > > * Разраб
> > > 
> > > * Прототипер
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Работает хорошо. Он не задумывается что по хорошему должны быть помимо Ведущего Разработчика **мейнтейнеры** которые будут отсеивать щиткод такого рода и **QA** которые будут тестить каждый новый механ перед обновой.
> > 
> > 
> > это вигерс написал, как проснется исправит, видимо забыл протестить. Или я в ближайшее время исправлю.
> 
> Просто по хорошему надо всегда делать тесты при **интеграции** кода. В гит все равно раньше сервера попадает. Просто сделать 2-3 опытных чела которые тебе **прошерстят новый механ или билд на поиск багов.**

слишком много мороки ради космонавтиков, это лишнее, ошибся человек, бывает.

**Comment by VigersRay** [comment]
> Ну типа, чел реально написал и даже не зашел в игру протестировать свое чудо, дабы увидеть настолько очевидные баги))) Почему я уже должен возвышать типа только за то, что он пишет код, даже не удостоившись его протестировать уделив на это 2-3 минуты?
> 
> По твоей логике если тип пишет код, то я должен его уважать уже просто за это? и плевать на то, что код просто ебаное халтурное дерьмо, которое он решил даже не проверять?
> 
> https://github.com/user-attachments/assets/8bc561cc-83db-4447-a0b9-4de20a0aef24
> 
> баг на столько очевидный и лежит на поверхности, что я решил даже не скидывать фрагмент с ним, но если это требуется...
> 
> Да и кодера я не оскорблял, я уверен, что у него есть более удачные работы, но вот этот "прыжок" реально хуйня.

Что за бредик, не занимайся пиздабольством, механика тестировалась, я прыгал через столы, мины, бездну и прочее. Но и подумать не мог что оно сработает с стеной.
Как пруфы зайди в медиа санрайза, там есть видео как я прыгаю на дебаг сборке.

**Comment by VigersRay** [comment]
решено
