### ISSUE TITLE
[Предложение]Фикс Баннихопа или Добавление предмета для баннихопа.

### ISSUE THREAD

**Issue by Fooksy2304** [space-sunrise/space-station-14#930]
Баннихоп прикольная механика, имеет место быть, но у неё есть ряд проблем:
1) стабильность- при поворотах периодически сбрасывается скорость.
как я понял, при соприкосновении с препятствием скорость действительно должна падать, но иногда это происходит и без прикосновения к препятствию, либо при крайне малом соприкосновении с таковым.
если потестить я уверен найдутся ещё некоторые проблемы, если я что то найду-напишу сюда
2)разгон-он слишком большой ,за 1 прыжок прирост составляет 5%,возможное решение проблемы: изменить показатель на 
1-2,5%
3) проход через стены-на большой скорости люди могут (вновь) проходить через стены-это произошло на моих глазах.
4) скорость слишком высокая, её ограничение в 100-130% от базового-оптимальный способ решения проблемы.
5) Логика-эта механика немного её ломает, возможный фикс-тратить выносливость за прыжки.
или Добавить интересную альтернативу, она описана ниже(при этом, при её применении следует отключить возможность набирать скорость без этой обуви).
ПРЫЖКОВАЯ ОБУВЬ(разрешает баннихоп)
Открывается заместо (ныне удалённых скороходов)-позволяют при прыжках набирать скорость.(в таком случае, можно оставить разгон в 5% прыжка,но с ограничением максимальной скорости,следует сделать механику(повторюсь) более стабильной.
Описание обуви: Благодаря нановолокнам  и специально разработанным магнитным подушкам, позволяет выполнять "баннихоп"-мечта любого любителя ретро-игр!.
КРОВАВО-КРАСНАЯ  ПРЫЖКОВАЯ ОБУВЬ (нескользящая) 
 стоимость 10тк 
 разгон 3%
 максимальная скорость 175% от базовой
 описание: улучшенная прыжковая обувь НТ. позволяет выполнять "баннихоп"-мечта любого любителя пиратских ретро-игр!.
 обе версии работают без аккумуляторов, заряжаются за счёт прыжков, тем самым они и  позволяют прыгать.
 при их наборе их максимальной скорости-можно добавить что то в духе молний из под ног-это будет показателем того что они работают на максимуме.
 Также можно добавить что после окончания прыжков, условную минуту будет оставаться прирост к скорости, который будет(в течении минуты) постепенно возвращаться к стандартной скорости ,после что бы набрать скорость обратно-придётся вновь делать расспрыжку, заряжая тем самым обувь.
 по сути это те-же самые скороходы, но требуют от владельца расспрыжки что бы набрать скорость.

**Comment by VigersRay** [comment]
по сути я достаточно урезал механику
