### ISSUE TITLE
[Баг] Эмоции прыжка убивают чат

### ISSUE THREAD

**Issue by W1mHack** [space-sunrise/space-station-14#933]
Огромнейшее количество эмоций прыжка - слишком сильно засоряет чат настолько, что находясь на рольке - рядом с одним прыгающим игроком, совсем не видно, что происходит в чате. Желательно снести все эмоции про прыжок, кроме сальтухи и выворачивания шеи. Так же поступает много жалоб конкретно на спам эмоциями

**Comment by VigersRay** [comment]
Решено чатстаком
