### ISSUE TITLE
[Баг] Энерго Оружие стреляет только в Станер Моде

### ISSUE THREAD

**Issue by KaiserMaus** [space-sunrise/space-station-14#934]
## Описание
Сейчас всё Энерго оружие (два ражима у которых) стреляет только станером, при попытке взять летальный режим автоматом меняет на станер

**Воспроизведение**
Взять любое энерго оружие(EnergyGun) Переключить режим и выстрелить

**Медиа**

**Дополнительный контекст**

**Comment by VigersRay** [comment]
Исправлено
