### ISSUE TITLE
[Предложение]Более щадящий "перелом шеи".

### ISSUE THREAD

**Issue by RastorFedor** [space-sunrise/space-station-14#962]
### Предложение
 - Сменить моментальный ваншот в 200 ушибов на условные 80-120 ушибов за одно неудачное сальто.
- Сменить моментальный ваншот в 200 ушибов на условные 20 ушибов и станкрит в 5 секунд при неудачном прыжке.
- Сменить возможный моментальный ваншот в 200 ушибов на постоянное нанесение 3-7 ушибов за подскальзывание.

### Причина
> Как-то не очень смешно, что на вроде как РП-проекте человек может вот так вот моментально умереть от таких мелочей, зато не может моментально умереть от того, что направленно на его убийство, когда выстрел в упор человека дробью даже не вводит его моментально в крит, зато неудачный прыжок способен моментально его ваншотнуть. Я удивлён, как Вигерс не додумался до вариантов "смертельно подвернуть ногу при беге" и "Насмерть поперхнуться едой".

**Comment by Kinar7** [comment]
Ебать, 5 минут? Да это же дольше того, сколько тебя будут поднимать медики

**Comment by VigersRay** [comment]
> ### Предложение
> * Сменить моментальный ваншот в 200 ушибов на условные 80-120 ушибов за одно неудачное сальто.
> * Сменить моментальный ваншот в 200 ушибов на условные 20 ушибов и станкрит в 5 секунд при неудачном прыжке.
> * Сменить возможный моментальный ваншот в 200 ушибов на постоянное нанесение 3-7 ушибов за подскальзывание.
> 
> ### Причина
> > Как-то не очень смешно, что на вроде как РП-проекте человек может вот так вот моментально умереть от таких мелочей, зато не может моментально умереть от того, что направленно на его убийство, когда выстрел в упор человека дробью даже не вводит его моментально в крит, зато неудачный прыжок способен моментально его ваншотнуть. Я удивлён, как Вигерс не додумался до вариантов "смертельно подвернуть ногу при беге" и "Насмерть поперхнуться едой".

Боже чел ты гений, обязательно добавлю вероятно удавиться едой если человек скажет что-то во время того как есть.

**Comment by VigersRay** [comment]
сделал перелом более щядящим.
