### ISSUE TITLE
[Предложение] Переработать роль Инструктора СБ

### ISSUE THREAD

**Issue by frakise** [space-sunrise/space-station-14#965]
Хочу сразу сказать, что эта предложка уже была одобрена Кайхарой, Вейном и Хеккрой, но почему-то так и не дошла до Шведа.

Проблема 1: роль Инструктора СБ, созданная для того чтобы тренировать кадетов, привела к тому что кадеты почти всю смену сидят с инструктором в бриге, их душат однотипными задачами в стиле подерись дубинкой, ответь на пару вопросов из КЗ, и документами на повышение из смены в смену, пока они не откроют офицера, что делает игру на кадете душным адом. В итоге из таких кадетов получаются офицеры с минимальной практикой работы офицера. Инструктор в данный момент приносит больше вреда чем пользы. Его нужно переделать и передавать кадетов офицерам чтобы они проходили с ними практику и нарабатывали опыт работы в СБ.

Проблема 2: кроме ГСБ никто не занимается контролем офицеров и кадетов на патрулях, не помогает ГСБ с выполнением его приказов, я считаю ГСБ нужна правая рука имеющая право выходить из брига, на которую можно положиться. На серверах до 140 человек онлайн, СБ критически не хватает младшего командного состава.

Проблема 3: в данный момент посадка некомпетентного офицера за халатность это событие которое можно увидеть раз в тысячу лет.

Решение:
Предлагаю сделать из Инструктора СБ - Сержанта

«Если ты мне понравишься, можешь звать меня «серж». Но знаешь что? Ты мне не нравишься!»

Сержант в иерархии СБ находится на третьем месте после Смотрителя.

СРП:

Сержант обязан:

1. Контролировать соблюдение СРП СБ, КЗ и ОПРС сотрудниками СБ кроме Смотрителя и ГСБ. При проявлении должностным лицом халатности вынести предупреждение, при повторном нарушении задержать сотрудника и действовать по всей строгости закона с применением модификатора должностное преступление.

2. Лично следить за выполнением работы отрядов на местах и в канале СБ, на протяжении смены вести актуальный список отрядов. Следить чтобы в каждом отряде было минимум по двое сотрудников.

3. Экспертно консультировать сотрудников СБ по любым вопросам в области СРП, КЗ и ОПРС, прилагать усилия к повышению квалификации личного состава.

4. Заполнять документы на понижение или увольнение некомпетентных сотрудников СБ и передать на подписание ГСБ, после чего проконтролировать исполнение документа.

Сержант имеет право:

1. Проводить процедуры обыска, изъятия контрабанды и улик, казни.

2. Проводить процедуры допроса и ареста  в отношении сотрудников СБ кроме Смотрителя и ГСБ.

3. Отдавать правомерные приказы сотрудникам СБ, кроме Смотрителя и ГСБ.

4. Замещать Смотрителя при его отсутствии. Замещать ГСБ при отсутствии Смотрителя и ГСБ.

5. В разумных пределах пренебрегать уставной речью при общении с сотрудниками СБ, кроме Смотрителя и ГСБ.

6. С разрешения или по приказу ГСБ принять обязанность по назначению отрядов.

7. Использовать в Зелёный код лишь общее снаряжение. В Синий код допускается использование нелетального вооружения. В Красный код допускается использование любого вооружения.

8. Рекомендовать компетентных кадетов на повышение до офицеров. Самостоятельно написать или принять от кадета свидетельство о повышении квалификации и запрос о повышении, проверить и передать на подписание ГСБ.

**Comment by frakise** [comment]
Вот ссылка на эту предложку в дискорде ласта
https://discord.com/channels/1253315855731916821/1280398015806443550

**Comment by KaiserMaus** [comment]
> Вот ссылка на эту предложку в дискорде ласта https://discord.com/channels/1253315855731916821/1280398015806443550

Ты не туда пришёл, иди в дискорд в раздел Вики предложений санрайза, тут Код, максимум могу изменить локализацию с Инструктора на Сержанта
