### ISSUE TITLE
[Предложение] Вернуть автозамену названий ролей персонала обратно на русскую.

### ISSUE THREAD

**Issue by frakise** [space-sunrise/space-station-14#967]
ГВ теперь СМ
ГСБ теперь ХоС
и так далее, это просто вводит несуразицу и неразбериху, сервер русскоязычный, и нет никакого смысла в этой автозамене. Это только создает проблемы в коммуникации между игроками.

**Comment by VigersRay** [comment]
Привыкайте и адаптируйтесь к английским названиям. Да храни америку Господь.
